# Generated by Django 2.0 on 2019-07-02 12:29

import apps.web.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20190702_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='no_links_preview',
            field=models.NullBooleanField(default=False, verbose_name='Disable links preview'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='no_notifications',
            field=models.NullBooleanField(default=False, verbose_name='Disable notifications'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='template_context',
            field=models.TextField(blank=True, default='{}', max_length=3000, null=True, validators=[apps.web.validators.json_field_validator], verbose_name='Template context'),
        ),
    ]
