# Generated by Django 2.0 on 2019-07-02 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20190702_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='rule',
            field=models.CharField(choices=[('full_coincidence', 'Full coincidence'), ('to_be_in', 'To be in'), ('contains', 'Contains'), ('starts_with', 'Starts with'), ('ends_with', 'Ends with'), ('match_regex', 'Match regex'), ('contain_an_image', 'Contain an image'), ('contain_a_file', 'Contain a file'), ('contain_an_audio', 'Contain a audio'), ('contain_a_video', 'Contain a video'), ('received_before', 'Received before'), ('received_after', 'Received after'), ('qr_code', 'QR code')], default='full_coincidence', max_length=255, verbose_name='Pattern'),
        ),
    ]
