# Generated by Django 2.0 on 2019-07-05 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20190702_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Entity created at', null=True, verbose_name='Created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Entity created at', null=True, verbose_name='Updated at')),
                ('step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='web.Step', verbose_name="User's level")),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='step',
        ),
        migrations.AddField(
            model_name='session',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appuser',
            name='current_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='web.Session', verbose_name="User's current session"),
        ),
    ]
